name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      directory:
        description: 'Select the directory (week) to build and push'
        required: true
        type: choice
        options:
          - week3
          - week4
          - week5
          - all
      image_tag:
        description: 'Tag for the Docker image (e.g., v1.0, latest)'
        required: true
        default: 'latest'
        type: string

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      directories: ${{ steps.set-dirs.outputs.directories }}
    steps:
      - id: set-dirs
        run: |
          if [ "${{ github.event.inputs.directory }}" = "all" ]; then
            echo 'directories=["week3", "week4", "week5"]' >> $GITHUB_OUTPUT
          else
            echo 'directories=["${{ github.event.inputs.directory }}"]' >> $GITHUB_OUTPUT
          fi

  docker-build-push:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ${{ fromJson(needs.prepare.outputs.directories) }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase repository owner
        id: prep
        run: |
          echo "OWNER_LOWERCASE=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_OUTPUT

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: ./Learn/${{ matrix.directory }}
          file: ./Learn/${{ matrix.directory }}/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ steps.prep.outputs.OWNER_LOWERCASE }}/playground-${{ matrix.directory }}:${{ github.event.inputs.image_tag }}
            ghcr.io/${{ steps.prep.outputs.OWNER_LOWERCASE }}/playground-${{ matrix.directory }}:latest
